[info]
title = "DataCube API"
description = """
An example for [axum] integration.

[axum]: https://crates.io/crates/axum
"""
contact = { url = "https://harpiya.com" }
license = "MIT"
version = "1.0"

[security_schemes.jwt_auth]
type = "http"
scheme = "bearer"
bearer_format = "JWT"

[[securities]]
name = "jwt_auth"
