name = "Users"
securities = []

[[endpoints]]
path = "/user/new"
method = "POST"
summary = "Creates a new user"

[endpoints.body]
schema = "/user/definition"

[[endpoints]]
path = "/user/{user_id}/delete"
method = "POST"
summary = "Deletes a user by ID"

[[endpoints]]
path = "/user/{user_id}/update"
method = "POST"
summary = "Updates a user by ID"

[endpoints.body]
schema = "/user/definition?action=update"

[[endpoints]]
path = "/user/{user_id}/view"
method = "GET"
summary = "Gets a user by ID"

[[endpoints]]
path = "/user/list"
method = "GET"
summary = "Finds a list of users"

[endpoints.query]
roles = { type = "string", description = "User roles" }
tags = { type = "string", description = "User tags" }

[endpoints.responses.200.headers]
server-timing = "string"
x-request-id = { type = "string", format = "uuid", description = "Request ID" }

[endpoints.responses.200.content]
status = "integer"
success = "boolean"
message = "string"
request_id = { type = "string", format = "uuid" }

[endpoints.responses.200.content.data]
type = "object"
entries = { type = "array", items = { schema = "/user/definition?action=list" } }
num_entries = { type = "integer", default = 10 }

[[endpoints]]
path = "/user/import"
method = "POST"
summary = "Imports the user data"

[endpoints.body]
schema = "/user/definition?action=import"

[[endpoints]]
path = "/user/export"
method = "GET"
summary = "Exports the user data"

[endpoints.query]
format = { type = "string", enum = ["csv", "json", "jsonlines"], default = "json", description = "File format" }
roles = { type = "string", description = "User roles" }
tags = { type = "string", description = "User tags" }

[schemas.userId]
type = "integer"
description = "User ID"

[models.user.status]
translations = [
    ["Active", "😄"],
    ["Inactive", "😴"],
]

[models.user.roles]
translations = [
    ["admin", "👮"],
    ["worker", "👷"],
]

[models.user.updated_at]
translations = [
    ["$span:24h", "Updated within 1 day"],
    ["$span:7d", "Updated within 1 week"],
]

