[package]
name = "harpiya-connector"
description = "Unified connector to data sources for harpiya."
version = "0.1.1"
rust-version = "1.85"
edition = "2024"

[package.metadata.docs.rs]
features = ["all-connectors"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
all-connectors = [
    "connector-arrow",
    "connector-http",
    "connector-mysql",
    "connector-postgres",
    "connector-sqlite",
]
connector-arrow = ["dep:datafusion", "harpiya-core/http-client"]
connector-http = [
    "dep:http",
    "dep:reqwest",
    "dep:percent-encoding",
    "dep:serde_json",
    "dep:serde_qs",
    "dep:url",
    "harpiya-core/http-client",
]
connector-mysql = ["dep:futures", "sqlx", "sqlx/mysql"]
connector-postgres = ["dep:futures", "sqlx", "sqlx/postgres"]
connector-sqlite = ["dep:futures", "sqlx", "sqlx/sqlite"]
default = ["connector-http"]

[dependencies]
apache-avro = "0.17.0"
regex = "1.11.1"
tracing = "0.1.41"

[dependencies.datafusion]
version = "42.2.0"
optional = true

[dependencies.futures]
version = "0.3.31"
optional = true

[dependencies.http]
version = "1.2.0"
optional = true

[dependencies.percent-encoding]
version = "2.3.1"
optional = true

[dependencies.reqwest]
version = "0.12.9"
optional = true
default-features = false
features = [
    "blocking",
    "gzip",
    "json",
    "multipart",
]

[dependencies.serde]
version = "1.0.216"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.134"
optional = true
features = ["raw_value"]

[dependencies.serde_qs]
version = "0.13.0"
optional = true

[dependencies.sqlx]
version = "0.8.2"
optional = true
default-features = false
features = [
    "chrono",
    "json",
    "rust_decimal",
    "uuid",
]

[dependencies.toml]
version = "0.8.19"
default-features = false

[dependencies.url]
version = "2.5.4"
optional = true

[dependencies.harpiya-core]
path = "../harpiya-core"
version = "0.30.1"
