[package]
name = "harpiya-storage"
description = "Files and storage services for harpiya."
version = "0.2.0"
rust-version = "1.85"
edition = "2024"

[package.metadata.docs.rs]
features = [
    "all-accessors",
    "http-client",
    "metrics",
]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
accessor = ["opendal"]
accessor-azblob = ["accessor", "opendal/services-azblob"]
accessor-azdls = ["accessor", "opendal/services-azdls"]
accessor-cacache = ["accessor", "opendal/services-cacache"]
accessor-cos = ["accessor", "opendal/services-cos"]
accessor-dashmap = ["accessor", "opendal/services-dashmap"]
accessor-dropbox = ["accessor", "opendal/services-dropbox"]
accessor-fs = ["accessor", "opendal/services-fs"]
accessor-gcs = ["accessor", "opendal/services-gcs"]
accessor-gdrive = ["accessor", "opendal/services-gdrive"]
accessor-ghac = ["accessor", "opendal/services-ghac"]
accessor-http = ["accessor", "opendal/services-http"]
accessor-ipfs = ["accessor", "opendal/services-ipfs"]
accessor-ipmfs = ["accessor", "opendal/services-ipmfs"]
accessor-memcached = ["accessor", "opendal/services-memcached"]
accessor-memory = ["accessor", "opendal/services-memory"]
accessor-mini-moka = ["accessor", "opendal/services-mini-moka"]
accessor-moka = ["accessor", "opendal/services-moka"]
accessor-mysql = ["accessor", "opendal/services-mysql"]
accessor-obs = ["accessor", "opendal/services-obs"]
accessor-onedrive = ["accessor", "opendal/services-onedrive"]
accessor-oss = ["accessor", "opendal/services-oss"]
accessor-persy = ["accessor", "opendal/services-persy"]
accessor-postgresql = ["accessor", "opendal/services-postgresql"]
accessor-redb = ["accessor", "opendal/services-redb"]
accessor-redis = ["accessor", "opendal/services-redis"]
accessor-s3 = ["accessor", "opendal/services-s3"]
accessor-sled = ["accessor", "opendal/services-sled"]
accessor-supabase = ["accessor", "opendal/services-supabase"]
accessor-webdav = ["accessor", "opendal/services-webdav"]
accessor-webhdfs = ["accessor", "opendal/services-webhdfs"]
all-accessors = [
    "accessor",
    "accessor-azblob",
    "accessor-azdls",
    "accessor-cacache",
    "accessor-cos",
    "accessor-dashmap",
    "accessor-dropbox",
    "accessor-fs",
    "accessor-gcs",
    "accessor-gdrive",
    "accessor-ghac",
    "accessor-http",
    "accessor-ipfs",
    "accessor-ipmfs",
    "accessor-memcached",
    "accessor-memory",
    "accessor-mini-moka",
    "accessor-moka",
    "accessor-mysql",
    "accessor-obs",
    "accessor-onedrive",
    "accessor-oss",
    "accessor-persy",
    "accessor-postgresql",
    "accessor-redb",
    "accessor-redis",
    "accessor-s3",
    "accessor-sled",
    "accessor-supabase",
    "accessor-webdav",
    "accessor-webhdfs",
]
http-client = ["dep:reqwest", "harpiya-core/http-client"]
metrics = ["opendal?/layers-metrics", "harpiya-core/metrics"]

[dependencies]
bytes = "1.9.0"
etag = "4.0.0"
md-5 = "0.10.6"
mime_guess = "2.0.5"
multer = "3.1.0"
tracing = "0.1.41"

[dependencies.opendal]
version = "0.50.2"
optional = true
default-features = false
features = ["layers-tracing"]

[dependencies.reqwest]
version = "0.12.9"
optional = true
default-features = false
features = [
    "blocking",
    "gzip",
    "json",
    "multipart",
]

[dependencies.toml]
version = "0.8.19"
default-features = false

[dependencies.harpiya-core]
path = "../harpiya-core"
version = "0.30.0"
features = ["http-client"]
